### ISSUE TITLE
Cannot get property 'lenght' on null object

### ISSUE THREAD

**Issue by Stakaitis** [epi2me-labs/wf-alignment#1]
Hi,

I'm not able to run this workflow - don't know why. 
The fastq folder only contains .fastq files. 
Ref folder contains .fa; .fa.fai and .fa.dict files from the same reference genome
Tried both with conda and singularity as -profile
Running the pipeline on Linux server

Getting this error:

N E X T F L O W  ~  version 21.10.0
Launching `epi2me-labs/wf-alignment` [backstabbing_hoover] - revision: b2dc3c8190 [master]
Core Nextflow options
  revision   : master
  runName    : backstabbing_hoover
  launchDir  : /faststorage/project/XY-Nanopore/pipelines/ont/alignment/run11_rna_4S
  workDir    : /faststorage/project/XY-Nanopore/pipelines/ont/alignment/run11_rna_4S/work
  projectDir : /home/stakatis/.nextflow/assets/epi2me-labs/wf-alignment
  userName   : stakatis
  profile    : conda
  configFiles: /home/stakatis/.nextflow/assets/epi2me-labs/wf-alignment/nextflow.config

Input/output options
  out_dir    : /faststorage/project/XY-Nanopore/data/rna/run11_rna_4S/epi2me/alignment/fastq_pass
  sample     : run11_non_non_non_LSMU_LE
  fastq      : /faststorage/project/XY-Nanopore/data/rna/run11_rna_4S/fastq_pass_NOgz

Reference genome options
  references : /faststorage/project/XY-Nanopore/data/reference/fasta/epi2me/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa

Other parameters
  wfversion  : v0.0.9

!! Only displaying parameters that differ from the pipeline defaults !!
------------------------------------------------------
If you use wf-alignment for your analysis please cite:

* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x

[-        ] process > start_ping:pingMessage -
Checking fastq input.
Single directory input detected.
Cannot get property 'length' on null object

 -- Check script '/home/stakatis/.nextflow/assets/epi2me-labs/wf-alignment/main.nf' at line: 328 or see '.nextflow.log' file for more details

Attaching .nextflow.log
[nextflow.log](https://github.com/epi2me-labs/wf-alignment/files/7730445/nextflow.log)

Any ideas what could be the problem?

**Comment by senidr** [comment]
I have exactly the same error

**Comment by sarahjeeeze** [comment]
For the --references parameter where you have specified one file, it just requires a directory as there may be more than one reference file. However will update to give a more useful error message.

**Comment by Stakaitis** [comment]
Hi @sarahjeeeze,

Thank you, that helped! Everything is working fine now.

What I've also noticed is that the --reference folder has to contain only .fasta or .fa files. If there is an indexed file .fai, then the pipeline doesn't like it.
Also, the `nextflow epi2me-labs/wf-alignment --help` says that --sample_sheet file has to contain 3 columns: "barcode", "sample_name" and "type". However, at least for version v.0.0.9, when ran through conda, if you provide this type of sample_sheet.csv file to the pipeline, it will give you an error, that sample_sheet.csv has to contain 2 columns: "barcode" and "sample_id" - not a complicated error to understand and fix, just wanted to point that out.

Happy New Years,
Rytis
