### ISSUE TITLE
[Bug]: wf-alignment does not allow input of reference sequence in Epi2Me Labs Windows Client v4.0.0

### ISSUE THREAD

**Issue by onkeld** [epi2me-labs/wf-alignment#10]
### What happened?

When setting up a run of wf-alignment in Epi2Me Labs V4.0.0 on Windows, the input for References does not allow me to select a .fasta file. The input only alliows selection of a folder and will not even show non-folder files in the selection dialogue:

![image](https://user-images.githubusercontent.com/207315/214355152-3a546d19-a5e6-4792-b7b0-f532550eabc6.png)

The following image shows the selection popup from Epi2Me Labs client which should contain a .fasta file in addition to the two subfolders. The .fasta file is not displayed as the input only accepts folders.
![image](https://user-images.githubusercontent.com/207315/214355265-f62d5a31-0e06-45fe-9593-4534ab6f3281.png)

Contents of the folder when opened in Explorer:
![image](https://user-images.githubusercontent.com/207315/214355730-59dfdfb0-5562-4945-b13c-ce0846203803.png)

If I select the folder containing my reference sequence .fasta file, the workflow immediately quits with Error:

´´´
N E X T F L O W  ~  version 22.04.5
Launching `/mnt/c/Users/daz87im/epi2melabs/workflows/epi2me-labs/wf-alignment/main.nf` [stoic_liskov] DSL2 - revision: f19d190a26
ERROR: Validation of pipeline parameters failed!
* Missing required parameter: --references
´´´

### Operating System

Windows 10

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - EPI2ME Labs Versions

4.0.0

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.2.4

### Relevant log output

```shell
N E X T F L O W  ~  version 22.04.5
Launching `/mnt/c/Users/daz87im/epi2melabs/workflows/epi2me-labs/wf-alignment/main.nf` [stoic_liskov] DSL2 - revision: f19d190a26
ERROR: Validation of pipeline parameters failed!
* Missing required parameter: --references
```

**Comment by onkeld** [comment]
Just updated Epi2Me Labs to v4.1.0 and the wf-alignment to v0.3.0 and the problem still exists.

If I select a folder containing reference sequences, I get the error message 
```
ERROR: Validation of pipeline parameters failed!

Missing required parameter: --references
```
Selecting a single reference .fasta file is not possible as the dialogue only allows for the selection of folders.

**Comment by onkeld** [comment]
Further debugging shows that one of my problem was that I was trying to load the data directly from my MinIon Mk1C via network access.
When copying the data to my local hard drive into my Epi2Me Labs folder which is also available from inside the docker container, the workflow will run.

In this case, the workflow also tries to use the reference sequences inside the folder I selected.

Still: The explanation says that I could either specify a reference fasta file or a folder containing reference fasta files. The software only allows specifying a folder.

**Comment by julibeg** [comment]
Many thanks for raising this, @onkeld!

> Still: The explanation says that I could either specify a reference fasta file or a folder containing reference fasta files. The software only allows specifying a folder.

The description has been updated to say that a folder is needed.

> Further debugging shows that one of my problem was that I was trying to load the data directly from my MinIon Mk1C via network access.
 When copying the data to my local hard drive into my Epi2Me Labs folder which is also available from inside the docker container, the workflow will run.
 
We are looking into fixing this in the app.

**Comment by julibeg** [comment]
Closing as using input data from network drives is currently not supported.
