### ISSUE TITLE
[not a bug] fastq inputs for wf_alignment

### ISSUE THREAD

**Issue by neurogenetics1** [epi2me-labs/wf-alignment#11]
### What happened?

I have two questions about the fastq input files. I ran the wf_basecaller pipeline and got aligned cram outputs. 

1-Is wf_alignment a required step, or does wf_alignment just convert cram to bam? Are the files in bam format required for the wf-human-variation, is that why wf_alignment converts them?

2-We had performed real-time guppy basecaller before, and we have fastq files called by guppy. 
How can I use and/or generate fastq inputs for the wf_alignment workflow using dorado?

Thank you in advance.

### Operating System

ubuntu 18.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

wf-alignment v0.3.3-g92f9558

### Relevant log output

```shell
.
```

**Comment by julibeg** [comment]
Hi there!

>I ran the wf_basecaller pipeline and got aligned cram outputs.

I don't quite understand, sorry. If you already aligned your reads during basecalling, why would you want to align them again (using wf-alignment)? Do you need to align them to a different reference?

> 1-Is wf_alignment a required step, or does wf_alignment just convert cram to bam? Are the files in bam format required for the wf-human-variation, is that why wf_alignment converts them?

Required for what? wf-alignment does not support CRAM at the moment. Supported input formats are FASTQ, BAM, and uBAM. If your goal is to run wf-human-variation, you don't need to run wf-alignment before.

>  How can I use and/or generate fastq inputs for the wf_alignment workflow using dorado?

It is now possible to run Dorado through [wf-basecalling](https://github.com/epi2me-labs/wf-basecalling).

**Comment by neurogenetics1** [comment]
Hi, thank you for your reply. I posted that issue in January. Since then, we were able to optimize basecaller pipeline. thank you :)
