### ISSUE TITLE
I have a single fastq as input, the workflow is trying to cat a fastq.gz file

### ISSUE THREAD

**Issue by yinshiyi** [epi2me-labs/wf-alignment#16]
### Operating System

macOS

### Workflow Version

v0.5.2

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

5.1.2

### CLI command run

I used the desktop

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

I used a single fastq file as input, the epic2me program is somehow trying to cat a fastq.gz file

### Relevant log output

```shell
Command executed:
  cat reads.fastq.gz     | minimap2 -t 2 -ax splice -uf combined_refs.fasta -     | samtools sort -@ 1 -o SRR25796772.sorted.aligned.bam -
```

### Application activity log entry

```shell
N E X T F L O W  ~  version 23.04.2
Launching `/Users/shiyiyin/epi2melabs/workflows/epi2me-labs/wf-alignment/main.nf` [eager_bohr] DSL2 - revision: 037262d299
||||||||||   _____ ____ ___ ____  __  __ _____      _       _
||||||||||  | ____|  _ \_ _|___ \|  \/  | ____|    | | __ _| |__  ___
|||||       |  _| | |_) | |  __) | |\/| |  _| _____| |/ _` | '_ \/ __|
|||||       | |___|  __/| | / __/| |  | | |__|_____| | (_| | |_) \__ \
||||||||||  |_____|_|  |___|_____|_|  |_|_____|    |_|\__,_|_.__/|___/
||||||||||  wf-alignment v0.5.2
--------------------------------------------------------------------------------
Core Nextflow options
  runName        : eager_bohr
  containerEngine: docker
  launchDir      : /Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX
  workDir        : /Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX/work
  projectDir     : /Users/shiyiyin/epi2melabs/workflows/epi2me-labs/wf-alignment
  userName       : shiyiyin
  profile        : standard
  configFiles    : /Users/shiyiyin/epi2melabs/workflows/epi2me-labs/wf-alignment/nextflow.config
Input Options
  fastq          : /Users/shiyiyin/Downloads/fastq
  references     : /Users/shiyiyin/Downloads/reference
Sample Options
  sample         : SRR25796772
Output Options
  out_dir        : /Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX/output
Advanced options
  minimap_preset : rna
!! Only displaying parameters that differ from the pipeline defaults !!
--------------------------------------------------------------------------------
If you use epi2me-labs/wf-alignment for your analysis please cite:
* The nf-core framework
  https://doi.org/10.1038/s41587-020-0439-x
--------------------------------------------------------------------------------
This is epi2me-labs/wf-alignment v0.5.2.
--------------------------------------------------------------------------------
Checking fastq input.
[64/62da43] Submitted process > pipeline:getVersions
[4f/eb449b] Submitted process > pipeline:getParams
[2c/960eb8] Submitted process > pipeline:process_references:combine
[54/cc1a9d] Submitted process > pipeline:process_references:fx2tab (1)
[f6/be6758] Submitted process > pipeline:addStepsColumn
[d7/3ca55a] Submitted process > fastcat_or_mv (1)
[f5/d7fcee] Submitted process > pipeline:alignReads (1)
ERROR ~ Error executing process > 'pipeline:alignReads (1)'
Caused by:
  Process `pipeline:alignReads (1)` terminated with an error exit status (1)
Command executed:
  cat reads.fastq.gz     | minimap2 -t 2 -ax splice -uf combined_refs.fasta -     | samtools sort -@ 1 -o SRR25796772.sorted.aligned.bam -
Command exit status:
  1
Command output:
  (empty)
Command error:
  samtools sort: failed to read header from "-"
Work dir:
  /Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX/work/f5/d7fcee81e80f672cfa43adc7f97bc4
Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
 -- Check '/Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX/nextflow.log' file for details
```

https://github.com/epi2me-labs/wf-alignment/blob/07e30d4b5ae6ee7a0a1c05d172fba0de5b733fad/main.nf#L33

The first line is checking if the input==fastq, which my file does, but why creating a fastq.gz file? 
https://github.com/epi2me-labs/wf-alignment/blob/07e30d4b5ae6ee7a0a1c05d172fba0de5b733fad/lib/ingress.nf#L75

not sure if I did something wrong here

**Comment by julibeg** [comment]
Hi @yinshiyi!

> `samtools sort: failed to read header from "-"`

This error indicates that `minimap2` did not produce an alignment file. Would you be able to go into `/Users/shiyiyin/epi2melabs/instances/wf-alignment_01HBHKQ0QW5V9GAJXDBXSHZXQX/work/f5/d7fcee81e80f672cfa43adc7f97bc4` and check that the FASTQ file is not empty (with `zcat reads.fastq.gz | wc -l`) and that there are references in `combined_refs.fasta`? If possible, it would also help if you could share the reference file(s) used so that I can try and reproduce the error.

**Comment by yinshiyi** [comment]
Hi @julibeg 
Absolutely, you are right about the samtools error, I think the beginning part might be wrong already, since cat fastq.gz will give non readable data.
I used hg19 from UCSC genome browser as reference 
Will also check the mini map output folder

**Comment by yinshiyi** [comment]
I did check zcat, it read fine.
I am puzzle that the pipeline will try to cat an intermediate file which is gz

**Comment by yinshiyi** [comment]
I did check zcat, it read fine.
I am puzzle that the pipeline will try to cat an intermediate file which is gz.


To reproduce the error

- Download and install epic2me on mac
- Wget hg19 from UCSC store under reference/
- GEO get the SRR direct RNA seq fastq file under fastq/
- run the align pipeline using the two folders

**Comment by julibeg** [comment]
Hi there and many thanks for the extra info.

> so perhaps the hg19 reference I got is too big for the pipeline

The pipeline itself doesn't care about the reference size, but your machine might be running out of memory. Docker Desktop limits the resources available to Docker containers. You can check / change these limits in Docker Desktop under `Settings > Resources > Advanced`. There is also a brief section on this in our [installation guide](https://labs.epi2me.io/installation/#resource-limits-on-macos). I would recommend setting this to 12GB or higher and trying again. If this doesn't fix the issue, please let us know!
