### ISSUE TITLE
Wrong description of sample sheet CSV

### ISSUE THREAD

**Issue by ulbivin** [epi2me-labs/wf-alignment#2]
Hi,

It seems the description of the sample sheet CSV file is wrong. It says to contain three columns:
CSV file with columns named `barcode`, `sample_name` and `type`. Permissible if passing a directory containing barcodeXX sub-directories.
but this gives an error:
OSError: Could not parse sample sheet, it must contain two columns named 'barcode' and 'sample_id' or 'alias'.

**Comment by sarahjeeeze** [comment]
Thanks for pointing this out, I will amend this in the upcoming release.
