### ISSUE TITLE
add @RG on Minimap2

### ISSUE THREAD

**Issue by Yoon90** [epi2me-labs/wf-alignment#21]
### Ask away!

Hello, I'm Yoon.

I've tried to use -R option testing add RG tag on minimap2 using this following command:

nextflow run epi2me-labs/wf-alignment --fastq wf-alignment-demo/fastq --references wf-alignment-demo/references --minimap_args "-r '@RG\tID:A00253_251_HTN2JDSXY.2\tPL:ILLUMINA\tLB:LB1\tSM:TA90'" --out_dir out_test

![image](https://github.com/epi2me-labs/wf-alignment/assets/134576692/7643888e-ac29-4d41-addf-f24f7832711c)

But it looks like it's not working and i could not figure out the problem.
Could check out the commnad line and figure out the problem?

Thank you
Best regards,
Giyoung.

**Comment by nrhorner** [comment]
Hi Yoon,

I think you need the `-R` minimap2 option, and your read group line should start with `@RG` (Although I think Github is interpreting your `@RG` as a user handle and displaying it lower case.

-R '`@RG`\tID:A00253_251_HTN2JDSXY.2\tPL:ILLUMINA\tLB:LB1\tSM:TA90'`

Neil

**Comment by nrhorner** [comment]
Hi @Yoon90 

One more thing. `--minimap_args` overrides all of the minimap2 args, so you will want to do something like:

```--minimap_args "-ax map-ont -R '@RG\tID:A00253_251_HTN2JDSXY.2\tPL:ILLUMINA\tLB:LB1\tSM:TA90'" ```

**Comment by Yoon90** [comment]
> Hi @Yoon90
> 
> One more thing. `--minimap_args` overrides all of the minimap2 args, so you will want to do something like:
> 
> `--minimap_args "-ax map-ont -R '@RG\tID:A00253_251_HTN2JDSXY.2\tPL:ILLUMINA\tLB:LB1\tSM:TA90'" `

Thank you!
