### ISSUE TITLE
Question about Map long cDNA reads

### ISSUE THREAD

**Issue by YIGUIz** [epi2me-labs/wf-alignment#25]
### Ask away!

Hello,
         I'm working on aligning cDNA RNA-seq ONT data. I noticed that the "--minimap_preset rna" parameter is designed for Nanopore Direct RNA-seq. Do I need to adjust the code in the Nextflow script for my datasets?
<img width="896" alt="截屏2024-02-28 14 43 08" src="https://github.com/epi2me-labs/wf-alignment/assets/64197852/39f3d39d-83ee-42a1-8828-849b2ed856e3">

**Comment by julibeg** [comment]
Hi @YIGUIz,

There's no need to change the code. You can provide arguments to be passed to minimap2 with the `--minimap_args` parameter (please note that this will override any preset arguments though).
