### ISSUE TITLE
Pipeline fails on non-NFS filesystems

### ISSUE THREAD

**Issue by TBradley27** [epi2me-labs/wf-alignment#27]
### Operating System

Other Linux (please specify below)

### Other Linux

Rocky Linux v8.6

### Workflow Version

v1.1.2-ge1fd7a5

### Workflow Execution

Command line

### CLI command run

```
nextflow run epi2me-labs/wf-alignment \
        -resume \
        -c my_config.cfg \
        -profile 'singularity' \
        --fastq wf-alignment-demo/fastq \
        --references wf-alignment-demo/references
```

### Workflow Execution - CLI Execution Profile

singularity

### What happened?

The pipeline failed at the 'move_or_compress_fq_file' step with no output in the working directory

### Relevant log output

```shell
Mar-18 14:45:31.108 [Task submitter] INFO  nextflow.Session - [88/9c0661] Submitted process > move_or_compress_fq_file (2)
Mar-18 14:49:00.407 [Task monitor] DEBUG nextflow.file.FileHelper - NFS path (false): /mnt/scratchc/jblab/bradle02/ONT/wf-alignment/work
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by TBradley27** [comment]
[.nextflow.log](https://github.com/epi2me-labs/wf-alignment/files/14638709/default.nextflow.log)
[slurm-32852310.out.txt](https://github.com/epi2me-labs/wf-alignment/files/14638715/slurm-32852310.out.txt)
[my_config.cfg.txt](https://github.com/epi2me-labs/wf-alignment/files/14638717/my_config.cfg.txt)

Thank you - I hope that helps. Just let me know if you need any more info

**Comment by julibeg** [comment]
Great, thanks!

Could you also send us the output of `sacct -j 32852311`?

**Comment by TBradley27** [comment]
Oops - I know the problem.

I didn't specify the correct parition/queue in my config file. This caused the pipeline to a default queue/partition which was not appropriate/available

I added the following line to my singularity profile to get this to work:

`process.queue = 'a_queue_that_I_can_use'`

Many thanks for guiding me to the root of the issue
