### ISSUE TITLE
Sporadic 141 exit status in pipeline:getVersions

### ISSUE THREAD

**Issue by waltergallegog** [epi2me-labs/wf-alignment#3]
Hello,
I'm getting an sporadic 141 error in the pipeline:getVersions process.
I'm using the profile conda option.

This is the content of versions.txt file when the issue occurs;
```
minimap2,2.24-r1122
samtools,1.15
```

I'm able to reproduce the issue as well by running manually:
```
bash -euo pipefail .command.sh
```
The issue is not 100% reproducible, sometimes it works and I get the full file:
```
minimap2,2.24-r1122
samtools,1.15
fastcat,0.4.10
mosdepth,0.3.3
aplanat,0.6.8
pysam,0.19.0
```

From a quick google search, it seems the issue could be in the samtools line, which explains why the script stops there.
```
samtools --version | head -n 1
```
The output of `samtools --version` is not small and it seems heads exits before samtools finishes.
https://unix.stackexchange.com/questions/580117/debugging-sporadic-141-shell-script-errors
(The issue in the link is for sort -nr followed by head, but I guess the same applies to our case)
>After head -1 does its job, it exits regardless if sort -nr managed to write all the data to the pipe. If sort has something more to write and head is no more then sort will get SIGPIPE. Nothing blows up. This is how pipes work. When you use head in a pipe you should not be surprised if the preceding command exits because of SIGPIPE.

**Comment by sarahjeeeze** [comment]
Hi thanks for this feedback, I will have a look in to it.

**Comment by waltergallegog** [comment]
Hi Sarah,
Thanks for the fix.
I will test it as soon as I have time.
For now I close the issue.
