### ISSUE TITLE
Varient calling pipline

### ISSUE THREAD

**Issue by exhgphan** [epi2me-labs/wf-alignment#30]
### Ask away!

Dear developer,

We are trying to use your wf-amplicon workflow on Epi2ME platform to quantify variants in amplicon libraries generated from the bacteria Desulfovibrio vulgaris. We are looking at multiple genes from this species. When we run the analysis, we get the following error:
“Warning: Analysis incomplete!The variant calling pipeline failed for all samples. Therefore, only a limited report is available. Consider relaxing the filtering criteria (e.g. using a lower value for --min_read_qual) as this is sometimes caused by filtering out all reads from the input data.”

We were hoping you could clarify this error for us as we have tried lowering the min-read-qual, reduced the minimum read length, and minimum number of reads but are still encountering this error.  The files we are trying to analyze are in the 'fasta_pass' folder from a recent Minion run. While we have posted to Nanopore's community forum we would like to check all of the boxes as my team has not found this specific error/warning on any help pages. 

We greatly appreciate any help! Thank you for your time.

**Comment by julibeg** [comment]
Hi @exhgphan,

Could you please provide the report produced by the workflow? Many thanks!

**Comment by julibeg** [comment]
Also, could you please re-open this issue in the [wf-amplicon](https://github.com/epi2me-labs/wf-amplicon) repository? This is the repo for wf-alignment. Thanks!

**Comment by exhgphan** [comment]
Hi Julien, 

I tried but it to switch to the wf-amplicon issue page brought me back to the wf-alignment issue page. Let me know how I should proceed.

**Comment by julibeg** [comment]
hmm, this is quite peculiar. Could you please click this link https://github.com/epi2me-labs/wf-amplicon/issues/new/choose and then click "Get started" under the "Question" panel? Let's see if that works. Thanks!
