### ISSUE TITLE
Local run of wf-alignment

### ISSUE THREAD

**Issue by mdillon3** [epi2me-labs/wf-alignment#32]
### Ask away!

I am running the wf-alignment workflow locally and after hours of processing (and using all default settings for memory and cores) I am getting a exit command fail 137.

I have included the params.json and the error report below. 
[params.json](https://github.com/user-attachments/files/15808577/params.json)
[Error Log - ONT.pdf](https://github.com/user-attachments/files/15808589/Error.Log.-.ONT.pdf)
[params.json](https://github.com/user-attachments/files/15808591/params.json)

**Comment by julibeg** [comment]
Hi @mdillon3 and thanks for raising this!

This shouldn't happen. We will investigate and come back to you. In the meantime, could you please export the complete logs of this run in the EPI2ME Desktop Application and share them here? You can do this by clicking on the "Report issue" button and then "Export".

Thanks!

**Comment by julibeg** [comment]
Also, could you please tell us the contents of the `/Users/mdillon3/Desktop/ncbi_dataset/ncbi_dataset/data/GCA_020975775.1` directory? Does it only contain the FASTA reference or other files as well?

**Comment by julibeg** [comment]
Closing for now as there was no more response. Please reopen if the issue persists.
