### ISSUE TITLE
With some datasets the fastcatUncompress process seems unnecessary and time consuming

### ISSUE THREAD

**Issue by waltergallegog** [epi2me-labs/wf-alignment#5]
Hello,
I'm running the workflow using a dataset consisting of one, very large fastq.gz file (64 G)
The file results form  running an experiment with the production basecaller from the PromethION version 20.06.18 (using Guppy 4.0.11).
It looks something like:
```
@7e6309fc-9f57-4acf-8d83-3589b9e446ca
AAATGTGCTTCGTTCAGTTGCATTGTGCTATATTCTAGATACAAGTATACA...
+
&&&$$##,,+*+4476364$%%%'$1*096+*)*'(,0)%%'***+(&'$%...
```

For this file, the step `fastcatUncompress` takes around 4 hours and 48 minutes , which is not negligible, considering the alignment takes 16h 41m using the default 4 threads. (and if I increase the number of threads I guess the effect is even worse as `fastcatUncompress` uses only one thread) (see image).
Looking at the resulting file generated at this step, it seems it is the same as the original input file because:

1. The input file is already in .gz format
2. There is only one input file, so there is nothing to concatenate
3. In the input fastq, there is no metadata information other than the sequence identifier. This means the function `fastq_header_to_SAM_tags.py` does nothing as well.

Is it possible to add the option to skip the `fastcatUncompress`, or to do it automatically based on the input file?

Thanks and BR.

![image](https://user-images.githubusercontent.com/5270762/166660883-32709f91-af37-46f8-a631-cec1069c4dc7.png)

**Comment by sarahjeeeze** [comment]
Hi, Thanks for the feedback. I will look at and test out the possibility of making this optional.

**Comment by sarahjeeeze** [comment]
Hi, We have now updated this in the most recent release.

**Comment by waltergallegog** [comment]
Hi Sarah,
Thanks for the fix.
I will test it as soon as I have time.
For now I close the issue.
