### ISSUE TITLE
Variable all not saved

### ISSUE THREAD

**Issue by giusmar** [epi2me-labs/wf-alignment#6]
https://github.com/epi2me-labs/wf-alignment/blob/f4f0de48ef5dfd11c12faa2710e27e27ca79f3fe/main.nf#L134

In this line, after the replace, the variable "all" is not modified as wanted with replace function. I added this line 

`all = all.replace(0, 1)`

**Comment by sarahjeeeze** [comment]
Hi, well spotted. I have updated it in the latest release. Thanks!

**Comment by giusmar** [comment]
Thank you too for the pipeline hehe
