### ISSUE TITLE
[Bug]: Interest of barcoder tool in the pipeline

### ISSUE THREAD

**Issue by abdeljalil-senhaji** [epi2me-labs/wf-alignment#9]
Hello,

You have to remove the barcoder tool from the environment.yml file because it blocks mamba from creating the conda environment.
I don't see the use of barcoder tool in the pipeline.
do you have an explanation ?

### Operating System

macOS

### Workflow Execution

Command line

### Workflow Execution - Execution Profile

Conda

### Workflow Version

*

### Relevant log output

```shell
*
```

**Comment by julibeg** [comment]
Closing as  `barcoder` is no longer used in the workflow and running the pipeline with `conda` has also been deprecated.
